# Generated by Django 3.2.8 on 2021-10-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_tital', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
